name: PR Guard

on:
  workflow_call:

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Fail if not from dev
        uses: actions/github-script@v7
        with:
          script: |
            const source = context.payload.pull_request.head.ref;
            const target = context.payload.pull_request.base.ref;

            if (target === "main" && source !== "dev") {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `🚫 PRs to **main** must come from \`dev\`.  
                This PR comes from \`${source}\`, please rebase or retarget.`
              });
              core.setFailed(`Invalid PR source branch: ${source}`);
            }
            if (target !== "main") {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `⚠️ PRs to branches other than **main** are not allowed.  
                This PR targets \`${target}\`, please retarget to **main**.`
              });
              core.setFailed(`Invalid PR target branch: ${target}`);
            }
            console.log(`PR source: ${source}, target: ${target}`);